-- GROUP BY 
SELECT 
DEPT_ID,
DEPARTMENT_NAME,
COUNT(*) AS TOTAL_PEOPLE
FROM EMPLOYEE_SALARY
INNER JOIN parks_departments
ON EMPLOYEE_SALARY.DEPT_ID=PARKS_DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPT_ID, DEPARTMENT_NAME;


-- HAVING CLAUSE 
SELECT 
DEPT_ID,
DEPARTMENT_NAME,
COUNT(*) AS TOTAL_PEOPLE
FROM EMPLOYEE_SALARY
INNER JOIN parks_departments
ON EMPLOYEE_SALARY.DEPT_ID=PARKS_DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPT_ID, DEPARTMENT_NAME
HAVING TOTAL_PEOPLE > 1;




